[theme]
base = "dark"
primaryColor = "#6366f1"
backgroundColor = "#0f1012"
secondaryBackgroundColor = "#1a1b1e"
textColor = "#f0f0f5"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
runOnSave = false
